# Generated by Django 5.2.17 on 2026-10-05 14:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalICTSystem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('criticality', models.CharField(choices=[('critical', 'Krytyczna funkcja'), ('important', 'Ważna funkcja'), ('standard', 'Standardowa')], default='standard', max_length=16, verbose_name='krytyczność')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='właściciel')),
            ],
            options={
                'verbose_name': 'historical system ICT',
                'verbose_name_plural': 'historical systemy ICT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ICTSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nazwa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('criticality', models.CharField(choices=[('critical', 'Krytyczna funkcja'), ('important', 'Ważna funkcja'), ('standard', 'Standardowa')], default='standard', max_length=16, verbose_name='krytyczność')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='właściciel')),
            ],
            options={
                'verbose_name': 'system ICT',
                'verbose_name_plural': 'systemy ICT',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCertificate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pem', models.TextField(blank=True, help_text='Wklej certyfikat (bez klucza prywatnego) – pola zostaną uzupełnione automatycznie.', verbose_name='certyfikat PEM')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nazwa')),
                ('common_name', models.CharField(blank=True, max_length=255, verbose_name='CN')),
                ('san', models.TextField(blank=True, verbose_name='SAN')),
                ('serial_number', models.CharField(blank=True, max_length=128, verbose_name='numer seryjny')),
                ('issuer', models.CharField(blank=True, max_length=512, verbose_name='wystawca')),
                ('fingerprint_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='odcisk SHA-256')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='ważny od')),
                ('not_after', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ważny do')),
                ('key_algorithm', models.CharField(blank=True, max_length=32, verbose_name='algorytm klucza')),
                ('key_size', models.PositiveIntegerField(default=0, verbose_name='rozmiar klucza')),
                ('kind', models.CharField(choices=[('tls_server', 'TLS serwer'), ('tls_client', 'TLS klient'), ('signing', 'Podpisywanie'), ('other', 'Inny')], default='tls_server', max_length=16, verbose_name='typ')),
                ('environment', models.CharField(choices=[('prod', 'Produkcja'), ('test', 'Test'), ('dev', 'Dev')], default='prod', max_length=8, verbose_name='środowisko')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='lokalizacja / użycie')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('renewed', 'Odnowiony'), ('revoked', 'Odwołany'), ('retired', 'Wycofany')], default='active', max_length=16, verbose_name='status')),
                ('renewed_at', models.DateField(blank=True, null=True, verbose_name='data odnowienia')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='właściciel')),
                ('ict_system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.ictsystem', verbose_name='system ICT')),
            ],
            options={
                'verbose_name': 'historical certyfikat',
                'verbose_name_plural': 'historical certyfikaty',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pem', models.TextField(blank=True, help_text='Wklej certyfikat (bez klucza prywatnego) – pola zostaną uzupełnione automatycznie.', verbose_name='certyfikat PEM')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nazwa')),
                ('common_name', models.CharField(blank=True, max_length=255, verbose_name='CN')),
                ('san', models.TextField(blank=True, verbose_name='SAN')),
                ('serial_number', models.CharField(blank=True, max_length=128, verbose_name='numer seryjny')),
                ('issuer', models.CharField(blank=True, max_length=512, verbose_name='wystawca')),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='odcisk SHA-256')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='ważny od')),
                ('not_after', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ważny do')),
                ('key_algorithm', models.CharField(blank=True, max_length=32, verbose_name='algorytm klucza')),
                ('key_size', models.PositiveIntegerField(default=0, verbose_name='rozmiar klucza')),
                ('kind', models.CharField(choices=[('tls_server', 'TLS serwer'), ('tls_client', 'TLS klient'), ('signing', 'Podpisywanie'), ('other', 'Inny')], default='tls_server', max_length=16, verbose_name='typ')),
                ('environment', models.CharField(choices=[('prod', 'Produkcja'), ('test', 'Test'), ('dev', 'Dev')], default='prod', max_length=8, verbose_name='środowisko')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='lokalizacja / użycie')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('renewed', 'Odnowiony'), ('revoked', 'Odwołany'), ('retired', 'Wycofany')], default='active', max_length=16, verbose_name='status')),
                ('renewed_at', models.DateField(blank=True, null=True, verbose_name='data odnowienia')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='właściciel')),
                ('ict_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='registry.ictsystem', verbose_name='system ICT')),
            ],
            options={
                'verbose_name': 'certyfikat',
                'verbose_name_plural': 'certyfikaty',
                'ordering': ['not_after'],
            },
        ),
    ]
