# Generated by Django 5.2.17 on 2026-10-05 14:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCertificateInstallation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('dns', 'DNS'), ('ip', 'IP Address')], max_length=3, verbose_name='typ adresu')),
                ('address', models.CharField(max_length=253, verbose_name='DNS / IP Address')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.certificate', verbose_name='certyfikat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lokalizacja instalacji',
                'verbose_name_plural': 'historical lokalizacje instalacji',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CertificateInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('dns', 'DNS'), ('ip', 'IP Address')], max_length=3, verbose_name='typ adresu')),
                ('address', models.CharField(max_length=253, verbose_name='DNS / IP Address')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='registry.certificate', verbose_name='certyfikat')),
            ],
            options={
                'verbose_name': 'lokalizacja instalacji',
                'verbose_name_plural': 'lokalizacje instalacji',
                'ordering': ['address_type', 'address'],
                'constraints': [models.UniqueConstraint(fields=('certificate', 'address_type', 'address'), name='unique_certificate_installation_address')],
            },
        ),
    ]
