# Generated by Django 5.2.17 on 2026-10-05 14:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_installation_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdb_id', models.CharField(max_length=128, unique=True, verbose_name='ID w CMDB')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa CI')),
                ('ict_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cmdb_items', to='registry.ictsystem', verbose_name='system ICT')),
            ],
            options={
                'verbose_name': 'element konfiguracji CMDB',
                'verbose_name_plural': 'elementy konfiguracji CMDB',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CMDBIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='adres IP')),
                ('configuration_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='registry.cmdbconfigurationitem', verbose_name='element konfiguracji CMDB')),
            ],
            options={
                'verbose_name': 'adres IP z CMDB',
                'verbose_name_plural': 'adresy IP z CMDB',
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='cmdb_ip',
            field=models.ForeignKey(blank=True, help_text='Wybierz IP z CMDB, aby powiązać instalację z CI i systemem ICT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_installations', to='registry.cmdbipaddress', verbose_name='adres IP z CMDB'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='cmdb_ip',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Wybierz IP z CMDB, aby powiązać instalację z CI i systemem ICT.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmdbipaddress', verbose_name='adres IP z CMDB'),
        ),
        migrations.CreateModel(
            name='HistoricalCMDBConfigurationItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cmdb_id', models.CharField(db_index=True, max_length=128, verbose_name='ID w CMDB')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa CI')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ict_system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.ictsystem', verbose_name='system ICT')),
            ],
            options={
                'verbose_name': 'historical element konfiguracji CMDB',
                'verbose_name_plural': 'historical elementy konfiguracji CMDB',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCMDBIPAddress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='adres IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('configuration_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmdbconfigurationitem', verbose_name='element konfiguracji CMDB')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical adres IP z CMDB',
                'verbose_name_plural': 'historical adresy IP z CMDB',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cmdbipaddress',
            constraint=models.UniqueConstraint(fields=('configuration_item', 'address'), name='unique_cmdb_ip_per_configuration_item'),
        ),
    ]
