# Generated by Django 5.2.17 on 2026-10-05 14:49

from django.db import migrations, models


def copy_cmdb_identifiers(apps, schema_editor):
    database = schema_editor.connection.alias
    Installation = apps.get_model("registry", "CertificateInstallation")
    HistoricalInstallation = apps.get_model("registry", "HistoricalCertificateInstallation")
    CMDBIPAddress = apps.get_model("registry", "CMDBIPAddress")
    CMDBConfigurationItem = apps.get_model("registry", "CMDBConfigurationItem")

    cmdb_ip_to_ci = dict(
        CMDBIPAddress.objects.using(database).values_list("id", "configuration_item_id")
    )
    ci_ids = {
        ci_id: cmdb_id
        for ci_id, cmdb_id in CMDBConfigurationItem.objects.using(database).values_list("id", "cmdb_id")
    }
    cmdb_ip_to_external_id = {
        cmdb_ip_id: ci_ids[ci_id]
        for cmdb_ip_id, ci_id in cmdb_ip_to_ci.items()
        if ci_id in ci_ids
    }

    installations = Installation.objects.using(database).exclude(cmdb_ip_id=None).iterator()
    batch = []
    for installation in installations:
        installation.cmdb_ci_id = cmdb_ip_to_external_id.get(installation.cmdb_ip_id, "")
        batch.append(installation)
        if len(batch) == 500:
            Installation.objects.using(database).bulk_update(batch, ("cmdb_ci_id",))
            batch.clear()
    if batch:
        Installation.objects.using(database).bulk_update(batch, ("cmdb_ci_id",))

    historical_installations = (
        HistoricalInstallation.objects.using(database).exclude(cmdb_ip_id=None).iterator()
    )
    history_batch = []
    for installation in historical_installations:
        installation.cmdb_ci_id = cmdb_ip_to_external_id.get(installation.cmdb_ip_id, "")
        history_batch.append(installation)
        if len(history_batch) == 500:
            HistoricalInstallation.objects.using(database).bulk_update(history_batch, ("cmdb_ci_id",))
            history_batch.clear()
    if history_batch:
        HistoricalInstallation.objects.using(database).bulk_update(history_batch, ("cmdb_ci_id",))


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_cmdb_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinstallation',
            name='cmdb_ci_id',
            field=models.CharField(blank=True, help_text='Stabilny identyfikator zasobu w zewnętrznej CMDB (nie nazwa ani adres URL).', max_length=128, verbose_name='ID CI w CMDB'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='cmdb_ci_id',
            field=models.CharField(blank=True, help_text='Stabilny identyfikator zasobu w zewnętrznej CMDB (nie nazwa ani adres URL).', max_length=128, verbose_name='ID CI w CMDB'),
        ),
        migrations.RunPython(copy_cmdb_identifiers, migrations.RunPython.noop),
    ]
