# Generated by Django 5.2.17 on 2026-10-05 15:08

from ipaddress import ip_address

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_cmdb_links(apps, schema_editor):
    database = schema_editor.connection.alias
    connection = schema_editor.connection
    Mapping = apps.get_model("registry", "CMDBIPMapping")
    Installation = apps.get_model("registry", "CertificateInstallation")
    HistoricalInstallation = apps.get_model("registry", "HistoricalCertificateInstallation")
    Certificate = apps.get_model("registry", "Certificate")
    LegacyCI = apps.get_model("registry", "CMDBConfigurationItem")
    LegacyIP = apps.get_model("registry", "CMDBIPAddress")
    HistoricalLegacyCI = apps.get_model("registry", "HistoricalCMDBConfigurationItem")
    HistoricalLegacyIP = apps.get_model("registry", "HistoricalCMDBIPAddress")
    HistoricalMapping = apps.get_model("registry", "HistoricalCMDBIPMapping")

    tables = set(connection.introspection.table_names())

    def columns_for(model):
        if model._meta.db_table not in tables:
            return set()
        with connection.cursor() as cursor:
            return {
                column.name
                for column in connection.introspection.get_table_description(
                    cursor, model._meta.db_table,
                )
            }

    installation_columns = columns_for(Installation)
    historical_installation_columns = columns_for(HistoricalInstallation)

    def valid_ip(value):
        try:
            return str(ip_address(value))
        except (TypeError, ValueError):
            return ""

    def mapping_for(address, ci_id, ict_system_id):
        if not address or not ci_id:
            return None
        address = valid_ip(address)
        if not address:
            return None
        mapping, _ = Mapping.objects.using(database).get_or_create(
            address=address,
            cmdb_ci_id=ci_id,
            defaults={"ict_system_id": ict_system_id},
        )
        return mapping.pk

    ip_mappings = {}
    current_ci = {}
    if LegacyCI._meta.db_table in tables and LegacyIP._meta.db_table in tables:
        current_ci = {
            item.pk: (item.cmdb_id, item.ict_system_id)
            for item in LegacyCI.objects.using(database).all().iterator()
        }
        for legacy_ip in LegacyIP.objects.using(database).iterator():
            ci_data = current_ci.get(legacy_ip.configuration_item_id)
            if ci_data is None:
                continue
            mapping_id = mapping_for(legacy_ip.address, ci_data[0], ci_data[1])
            if mapping_id:
                ip_mappings[legacy_ip.pk] = mapping_id

        historical_ci = {}
        if HistoricalLegacyCI._meta.db_table in tables:
            for item in HistoricalLegacyCI.objects.using(database).order_by(
                "history_date", "history_id",
            ).iterator():
                historical_ci[item.id] = (item.cmdb_id, item.ict_system_id)

        if HistoricalLegacyIP._meta.db_table in tables:
            historical_ip_columns = columns_for(HistoricalLegacyIP)
            if "configuration_item_id" in historical_ip_columns:
                for legacy_ip in HistoricalLegacyIP.objects.using(database).iterator():
                    ci_data = current_ci.get(legacy_ip.configuration_item_id)
                    if ci_data is None:
                        ci_data = historical_ci.get(legacy_ip.configuration_item_id)
                    if ci_data is None:
                        continue
                    address = valid_ip(legacy_ip.address)
                    if not address:
                        continue
                    history_fields = {
                        "id": legacy_ip.id,
                        "address": address,
                        "cmdb_ci_id": ci_data[0],
                        "ict_system_id": ci_data[1],
                        "history_date": legacy_ip.history_date,
                        "history_change_reason": legacy_ip.history_change_reason,
                        "history_type": legacy_ip.history_type,
                    }
                    if "history_user_id" in historical_ip_columns:
                        history_fields["history_user_id"] = legacy_ip.history_user_id
                    HistoricalMapping.objects.using(database).create(**history_fields)

    installation_fields = [
        "pk", "address", "address_type", "cmdb_ci_id", "certificate_id",
    ]
    if "cmdb_ip_id" in installation_columns:
        installation_fields.append("cmdb_ip_id")
    certificate_systems = dict(
        Certificate.objects.using(database).values_list("pk", "ict_system_id")
    )
    for installation in Installation.objects.using(database).values(
        *installation_fields,
    ).iterator():
        legacy_ip_id = installation.get("cmdb_ip_id")
        mapping_id = mapping_for(
            installation["address"],
            installation["cmdb_ci_id"] if installation["address_type"] == "ip" else "",
            certificate_systems.get(installation["certificate_id"]),
        )
        mapping_id = ip_mappings.get(legacy_ip_id, mapping_id)
        changes = {}
        if mapping_id:
            changes["cmdb_mapping_id"] = mapping_id
            changes["address"] = valid_ip(installation["address"])
        system_id = certificate_systems.get(installation["certificate_id"])
        if system_id:
            changes["ict_system_id"] = system_id
        if changes:
            Installation.objects.using(database).filter(
                pk=installation["pk"],
            ).update(**changes)

    historical_installation_fields = [
        "history_id", "address", "address_type", "cmdb_ci_id", "certificate_id",
    ]
    if "cmdb_ip_id" in historical_installation_columns:
        historical_installation_fields.append("cmdb_ip_id")
    for installation in HistoricalInstallation.objects.using(database).values(
        *historical_installation_fields,
    ).iterator():
        legacy_ip_id = installation.get("cmdb_ip_id")
        certificate_system_id = certificate_systems.get(installation["certificate_id"])
        mapping_id = mapping_for(
            installation["address"],
            installation["cmdb_ci_id"] if installation["address_type"] == "ip" else "",
            certificate_system_id,
        )
        mapping_id = ip_mappings.get(legacy_ip_id, mapping_id)
        changes = {}
        if mapping_id:
            changes["cmdb_mapping_id"] = mapping_id
            changes["address"] = valid_ip(installation["address"])
        if certificate_system_id:
            changes["ict_system_id"] = certificate_system_id
        if changes:
            HistoricalInstallation.objects.using(database).filter(
                history_id=installation["history_id"],
            ).update(**changes)


def restore_legacy_cmdb_links(apps, schema_editor):
    database = schema_editor.connection.alias
    Mapping = apps.get_model("registry", "CMDBIPMapping")
    Installation = apps.get_model("registry", "CertificateInstallation")
    HistoricalInstallation = apps.get_model("registry", "HistoricalCertificateInstallation")
    cmdb_ids = dict(
        Mapping.objects.using(database).values_list("id", "cmdb_ci_id")
    )

    for installation in Installation.objects.using(database).exclude(
        cmdb_mapping_id=None,
    ).values("pk", "cmdb_mapping_id"):
        ci_id = cmdb_ids.get(installation["cmdb_mapping_id"], "")
        if ci_id:
            Installation.objects.using(database).filter(
                pk=installation["pk"],
            ).update(cmdb_ci_id=ci_id)

    for installation in HistoricalInstallation.objects.using(database).exclude(
        cmdb_mapping_id=None,
    ).values("history_id", "cmdb_mapping_id"):
        ci_id = cmdb_ids.get(installation["cmdb_mapping_id"], "")
        if ci_id:
            HistoricalInstallation.objects.using(database).filter(
                history_id=installation["history_id"],
            ).update(cmdb_ci_id=ci_id)


def remove_obsolete_cmdb_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="registry",
        codename__regex=(
            r"^(view|add|change|delete)_"
            r"(cmdbconfigurationitem|historicalcmdbconfigurationitem|"
            r"cmdbipaddress|historicalcmdbipaddress)$"
        ),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_remove_historicalcmdbipaddress_configuration_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBIPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='adres IP')),
                ('cmdb_ci_id', models.CharField(max_length=128, verbose_name='ID CI w CMDB')),
            ],
            options={
                'verbose_name': 'mapowanie IP z CMDB',
                'verbose_name_plural': 'mapowania IP z CMDB',
                'ordering': ['address', 'cmdb_ci_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCMDBIPMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='adres IP')),
                ('cmdb_ci_id', models.CharField(max_length=128, verbose_name='ID CI w CMDB')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical mapowanie IP z CMDB',
                'verbose_name_plural': 'historical mapowania IP z CMDB',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='certificateinstallation',
            name='unique_certificate_installation_address',
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='ict_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_installations', to='registry.ictsystem', verbose_name='system ICT'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ostatnio widziano'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='port'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='protocol',
            field=models.CharField(blank=True, max_length=32, verbose_name='protokół'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='repository',
            field=models.CharField(blank=True, max_length=128, verbose_name='repozytorium Tenable'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='source',
            field=models.CharField(choices=[('manual', 'Ręcznie'), ('tenable', 'Tenable.sc')], default='manual', max_length=8, verbose_name='źródło'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='ict_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.ictsystem', verbose_name='system ICT'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ostatnio widziano'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='port'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='protocol',
            field=models.CharField(blank=True, max_length=32, verbose_name='protokół'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='repository',
            field=models.CharField(blank=True, max_length=128, verbose_name='repozytorium Tenable'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='source',
            field=models.CharField(choices=[('manual', 'Ręcznie'), ('tenable', 'Tenable.sc')], default='manual', max_length=8, verbose_name='źródło'),
        ),
        migrations.AddField(
            model_name='cmdbipmapping',
            name='ict_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmdb_ip_mappings', to='registry.ictsystem', verbose_name='system ICT'),
        ),
        migrations.AddField(
            model_name='certificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_installations', to='registry.cmdbipmapping', verbose_name='mapowanie IP z CMDB'),
        ),
        migrations.AddField(
            model_name='historicalcertificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmdbipmapping', verbose_name='mapowanie IP z CMDB'),
        ),
        migrations.AddConstraint(
            model_name='certificateinstallation',
            constraint=models.UniqueConstraint(fields=('certificate', 'address_type', 'address', 'source', 'port', 'protocol', 'repository'), name='unique_certificate_installation_endpoint'),
        ),
        migrations.AddField(
            model_name='historicalcmdbipmapping',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcmdbipmapping',
            name='ict_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.ictsystem', verbose_name='system ICT'),
        ),
        migrations.AddConstraint(
            model_name='cmdbipmapping',
            constraint=models.UniqueConstraint(fields=('address', 'cmdb_ci_id'), name='unique_cmdb_ip_ci_mapping'),
        ),
        migrations.RunPython(migrate_legacy_cmdb_links, restore_legacy_cmdb_links),
        migrations.RemoveField(
            model_name='certificateinstallation',
            name='cmdb_ci_id',
        ),
        migrations.RemoveField(
            model_name='historicalcertificateinstallation',
            name='cmdb_ci_id',
        ),
        migrations.RunPython(remove_obsolete_cmdb_permissions, migrations.RunPython.noop),
    ]
