# Generated by Django 5.2.17 on 2026-10-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_remove_legacy_cmdb_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmdbipmapping',
            options={'ordering': ['address', 'cmdb_ci_id'], 'verbose_name': 'zasób CMDB', 'verbose_name_plural': 'zasoby CMDB'},
        ),
        migrations.AlterModelOptions(
            name='historicalcmdbipmapping',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical zasób CMDB', 'verbose_name_plural': 'historical zasoby CMDB'},
        ),
        migrations.AlterField(
            model_name='certificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_installations', to='registry.cmdbipmapping', verbose_name='zasób CMDB'),
        ),
        migrations.AlterField(
            model_name='historicalcertificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmdbipmapping', verbose_name='zasób CMDB'),
        ),
    ]
