# Generated by Django 5.2.17 on 2026-10-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_rename_cmdb_mapping_as_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, help_text='Dotyczy lokalizacji IP Address. Łączy znaleziony adres IP z rekordem CI; system ICT może zostać uzupełniony z zasobu.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_installations', to='registry.cmdbipmapping', verbose_name='powiązanie z zasobem CMDB (IP)'),
        ),
        migrations.AlterField(
            model_name='historicalcertificateinstallation',
            name='cmdb_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dotyczy lokalizacji IP Address. Łączy znaleziony adres IP z rekordem CI; system ICT może zostać uzupełniony z zasobu.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmdbipmapping', verbose_name='powiązanie z zasobem CMDB (IP)'),
        ),
    ]
