# Generated by Django 5.2.17 on 2026-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_clarify_cmdb_asset_address_autofill'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalictsystem',
            name='cmdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stabilny identyfikator systemu w zewnętrznej CMDB.', max_length=128, null=True, verbose_name='CMDB_ID'),
        ),
        migrations.AddField(
            model_name='ictsystem',
            name='cmdb_id',
            field=models.CharField(blank=True, help_text='Stabilny identyfikator systemu w zewnętrznej CMDB.', max_length=128, null=True, unique=True, verbose_name='CMDB_ID'),
        ),
    ]
