# Generated by Django 5.2.17 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_add_ict_system_cmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbipmapping',
            name='cmdb_ci_id',
            field=models.CharField(max_length=128, verbose_name='ID CI zasobu'),
        ),
        migrations.AlterField(
            model_name='historicalcmdbipmapping',
            name='cmdb_ci_id',
            field=models.CharField(max_length=128, verbose_name='ID CI zasobu'),
        ),
    ]
