# Generated by Django 5.2.17 on 2026-10-07 11:04

from django.db import migrations, models


def move_important_systems_to_standard(apps, schema_editor):
    ICTSystem = apps.get_model("registry", "ICTSystem")
    ICTSystem.objects.using(schema_editor.connection.alias).filter(
        criticality="important",
    ).update(criticality="standard")


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_rename_ict_system_cmdb_id_to_snsi'),
    ]

    operations = [
        migrations.RunPython(move_important_systems_to_standard, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicalictsystem',
            name='criticality',
            field=models.CharField(choices=[('critical', 'Krytyczna funkcja'), ('standard', 'Standardowa')], default='standard', max_length=16, verbose_name='krytyczność'),
        ),
        migrations.AlterField(
            model_name='ictsystem',
            name='criticality',
            field=models.CharField(choices=[('critical', 'Krytyczna funkcja'), ('standard', 'Standardowa')], default='standard', max_length=16, verbose_name='krytyczność'),
        ),
    ]
