# Generated by Django 5.2.17 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_alter_historicalictsystem_criticality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbipmapping',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nazwa'),
        ),
        migrations.AddField(
            model_name='historicalcmdbipmapping',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='cmdbipmapping',
            name='cmdb_ci_id',
            field=models.CharField(max_length=128, verbose_name='ID Zasobu'),
        ),
        migrations.AlterField(
            model_name='historicalcmdbipmapping',
            name='cmdb_ci_id',
            field=models.CharField(max_length=128, verbose_name='ID Zasobu'),
        ),
    ]
